services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./shared-data:/data
    depends_on:
      - whisper
      - aligner

  whisper:
    build: ./whisper
    container_name: whisper
    ports:
      - "8001:8001"
    volumes:
      - ./model-cache:/root/.cache
      - ./whisper:/app
      - ./shared-data:/data

  aligner:
    build: ./aligner
    container_name: aligner
    ports:
      - "8002:8000"
    volumes:
      - ./aligner:/app
      - ./shared-data:/data
      - ./model-cache/mfa:/mfa
